version: '3.8'

services:
  api:
    build: ./api-commits
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  client:
    build: ./front-commits
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
